# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T19:17:10+00:00

from __future__ import annotations

from enum import Enum


class Format(Enum):
    json = 'json'
    xml = 'xml'
